### ISSUE TITLE
Run versions I specify

### ISSUE THREAD

**Issue by coryhouse** [oyedeyeye/alc-js-dev-env#1]
https://github.com/coryhouse/javascript-development-environment/issues/33

**Comment by oyedeyeye** [comment]
Thank you @coryhouse .
After running the specified version. I got this error when I got to Automation.
**It throws error on adding _"prestart": "node buildScripts/startMessage.js",_**
**Find the state of my files in this Commit** [ 6cc3bd6](https://github.com/oyedeyeye/alc-js-dev-env/tree/6cc3bd6e6a3b57dd397e55b5424cd38951948537)


`C:\Users\XYXYXYXY\WEB_Project\ALC_4.0\alc-js-dev-env\buildScripts\startMessage.js:1
import chalk from 'chalk';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)       
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! javascript-development-environment@1.0.0 prestart: `node buildScripts/startMessage.js`npm ERR!
npm ERR! Failed at the javascript-development-environment@1.0.0 prestart script.   
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XYXYXYXY\AppData\Roaming\npm-cache\_logs\2019-08-24T06_34_38_859Z-debug.log`

**Comment by oyedeyeye** [comment]
it has been fixed @coryhouse  I still have my Es6 inside startMessage.js
the Import doesn't work there.

I found this out when I got to **BABEL** configuration section of the tutorial
